package com.sofis.entities.codigueras;

/**
 * Constantes para usar en el atributo código de la configuracion.
 *
 * @author Usuario
 */
public class ConfiguracionCodigos {

    public static String FILTRO_INICIO_POR_AREAS = "FILTRO_INICIO_POR_AREAS";
    public static String RIESGO_TIEMPO_LIMITE_AMARILLO = "RIESGO_TIEMPO_LIMITE_AMARILLO";
    public static String RIESGO_TIEMPO_LIMITE_ROJO = "RIESGO_TIEMPO_LIMITE_ROJO";
    public static String RIESGO_INDICE_LIMITE_AMARILLO = "RIESGO_INDICE_LIMITE_AMARILLO";
    public static String RIESGO_INDICE_LIMITE_ROJO = "RIESGO_INDICE_LIMITE_ROJO";
    public static String RIESGO_FECHA_LIMITE_CANT_DIAS = "RIESGO_FECHA_LIMITE_CANT_DIAS";
    public static String DOCUMENTO_PORCENTAJE_LIMITE_AMARILLO = "DOCUMENTO_PORCENTAJE_LIMITE_AMARILLO";
    public static String DOCUMENTO_PORCENTAJE_LIMITE_ROJO = "DOCUMENTO_PORCENTAJE_LIMITE_ROJO";
    public static String TAMANIO_MAX_ARCHIVO_DOCUMENTO = "TAMANIO_MAX_ARCHIVO_DOCUMENTO";
    public static String TAMANIO_MAX_ARCHIVO_MULTIMEDIA = "TAMANIO_MAX_ARCHIVO_MULTIMEDIA";
    public static String COSTO_ACTUAL_LIMITE_AMARILLO = "COSTO_ACTUAL_LIMITE_AMARILLO";
    public static String COSTO_ACTUAL_LIMITE_ROJO = "COSTO_ACTUAL_LIMITE_ROJO";
    public static String ESTADO_INICIO_LIMITE_ROJO = "ESTADO_INICIO_LIMITE_ROJO";
    public static String ESTADO_INICIO_LIMITE_AMARILLO = "ESTADO_INICIO_LIMITE_AMARILLO";
    public static String ESTADO_PLANIFICACION_LIMITE_ROJO = "ESTADO_PLANIFICACION_LIMITE_ROJO";
    public static String ESTADO_PLANIFICACION_LIMITE_AMARILLO = "ESTADO_PLANIFICACION_LIMITE_AMARILLO";
    public static String PRODUCTO_INDICE_LIMITE_AMARILLO = "PRODUCTO_INDICE_LIMITE_AMARILLO";
    public static String PRODUCTO_INDICE_LIMITE_ROJO = "PRODUCTO_INDICE_LIMITE_ROJO";
    public static String TAMANIO_MAX_LOGO_ORGANISMO = "TAMANIO_MAX_LOGO_ORGANISMO";
    public static String MAIL_FROM = "MAIL_FROM";
    public static String MAIL_TLS = "MAIL_TLS";
    public static String MAIL_ENCODING = "MAIL_ENCODING";
    public static String CON_CORREO = "CON_CORREO";
    public static String CON_CONTROL_ACCESO = "CON_CONTROL_ACCESO";
    public static String ENVIO_NOTIFICACIONES = "ENVIO_NOTIFICACIONES";
    public static String HORA_NOTIFICACIONES = "HORA_NOTIFICACIONES";
    public static String ADJUNTO_MODIFICA_PRESUPUESTO = "ADJUNTO_MODIFICA_PRESUPUESTO";
    public static String CURRENT_LOCALE_LANGUAGE = "CURRENT_LOCALE_LANGUAGE";
    public static String CURRENT_LOCALE_COUNTRY = "CURRENT_LOCALE_COUNTRY";
    public static String CALIDAD_LIMITE_AMARILLO = "CALIDAD_LIMITE_AMARILLO";
    public static String CALIDAD_LIMITE_ROJO = "CALIDAD_LIMITE_ROJO";
    public static String CALIDAD_GERENTE_MODIFICA = "CALIDAD_GERENTE_MODIFICA";
    public static String FOLDER_MEDIA = "FOLDER_MEDIA";

}
