package com.sofis.entities.codigueras;

/**
 * Constantes para usar en el atributo código de la configuracion.
 *
 * @author Usuario
 */
public class ConfiguracionCodigos {

    public static String IS_DESARROLLO = "IS_DESARROLLO";
    public static String DATABASE_ENGINE = "DATABASE_ENGINE";
    public static String DATABASE_SCHEMA = "DATABASE_SCHEMA";

    public static String FILTRO_INICIO_POR_AREAS = "FILTRO_INICIO_POR_AREAS";
    public static String RIESGO_TIEMPO_LIMITE_AMARILLO = "RIESGO_TIEMPO_LIMITE_AMARILLO";
    public static String RIESGO_TIEMPO_LIMITE_ROJO = "RIESGO_TIEMPO_LIMITE_ROJO";
    public static String RIESGO_INDICE_LIMITE_AMARILLO = "RIESGO_INDICE_LIMITE_AMARILLO";
    public static String RIESGO_INDICE_LIMITE_ROJO = "RIESGO_INDICE_LIMITE_ROJO";
    public static String RIESGO_FECHA_LIMITE_CANT_DIAS = "RIESGO_FECHA_LIMITE_CANT_DIAS";
    public static String DOCUMENTO_PORCENTAJE_LIMITE_AMARILLO = "DOCUMENTO_PORCENTAJE_LIMITE_AMARILLO";
    public static String DOCUMENTO_PORCENTAJE_LIMITE_ROJO = "DOCUMENTO_PORCENTAJE_LIMITE_ROJO";
    public static String TAMANIO_MAX_ARCHIVO_DOCUMENTO = "TAMANIO_MAX_ARCHIVO_DOCUMENTO";
    public static String TAMANIO_MAX_ARCHIVO_MANUAL_USUARIO = "TAMANIO_MAX_ARCHIVO_MANUAL_USUARIO";
    public static String TAMANIO_MAX_ARCHIVO_MULTIMEDIA = "TAMANIO_MAX_ARCHIVO_MULTIMEDIA";
    public static String COSTO_ACTUAL_LIMITE_AMARILLO = "COSTO_ACTUAL_LIMITE_AMARILLO";
    public static String COSTO_ACTUAL_LIMITE_ROJO = "COSTO_ACTUAL_LIMITE_ROJO";
    public static String ESTADO_INICIO_LIMITE_ROJO = "ESTADO_INICIO_LIMITE_ROJO";
    public static String ESTADO_INICIO_LIMITE_AMARILLO = "ESTADO_INICIO_LIMITE_AMARILLO";
    public static String ESTADO_PLANIFICACION_LIMITE_ROJO = "ESTADO_PLANIFICACION_LIMITE_ROJO";
    public static String ESTADO_PLANIFICACION_LIMITE_AMARILLO = "ESTADO_PLANIFICACION_LIMITE_AMARILLO";
    public static String PRODUCTO_INDICE_LIMITE_AMARILLO = "PRODUCTO_INDICE_LIMITE_AMARILLO";
    public static String PRODUCTO_INDICE_LIMITE_ROJO = "PRODUCTO_INDICE_LIMITE_ROJO";
    public static String ALCANCE_INDICE_LIMITE_AMARILLO = "ALCANCE_INDICE_LIMITE_AMARILLO";
    public static String ALCANCE_INDICE_LIMITE_ROJO = "ALCANCE_INDICE_LIMITE_ROJO";
    public static String TAMANIO_MAX_LOGO_ORGANISMO = "TAMANIO_MAX_LOGO_ORGANISMO";
    public static String MAIL_FROM = "MAIL_FROM";
    public static String MAIL_TLS = "MAIL_TLS";
    public static String MAIL_DEBUG = "MAIL_DEBUG";
    public static String MAIL_ENCODING = "MAIL_ENCODING";
    public static String CON_CORREO = "CON_CORREO";
    public static String CON_CONTROL_ACCESO = "CON_CONTROL_ACCESO";
    public static String ENVIO_NOTIFICACIONES = "ENVIO_NOTIFICACIONES";
    public static String HORA_NOTIFICACIONES = "HORA_NOTIFICACIONES";
    public static String ADJUNTO_MODIFICA_PRESUPUESTO = "ADJUNTO_MODIFICA_PRESUPUESTO";
    public static String CURRENT_LOCALE_LANGUAGE = "CURRENT_LOCALE_LANGUAGE";
    public static String CURRENT_LOCALE_COUNTRY = "CURRENT_LOCALE_COUNTRY";
    public static String CALIDAD_LIMITE_AMARILLO = "CALIDAD_LIMITE_AMARILLO";
    public static String CALIDAD_LIMITE_ROJO = "CALIDAD_LIMITE_ROJO";
    public static String CALIDAD_GERENTE_MODIFICA = "CALIDAD_GERENTE_MODIFICA";
    public static String FOLDER_MEDIA = "FOLDER_MEDIA";
    public static String USAR_PGE = "USAR_PGE";

    public static String VISUALIZADOR_EXPORTACION_POR_PGE = "VISUALIZADOR_EXPORTACION_POR_PGE";

    //Publicar Proyecto
    public static String VISUALIZADOR_PUBLICARSERVICIO_URLLOGICA = "VISUALIZADOR.PUBLICARSERVICIO_URLLOGICA";
    public static String VISUALIZADOR_PUBLICARSERVICIO_SOAPACTION = "VISUALIZADOR.PUBLICARSERVICIO_SOAPACTION";
    public static String VISUALIZADOR_PUBLICARSERVICIO_NAMESPACE = "VISUALIZADOR.PUBLICARSERVICIO_NAMESPACE";
    public static String VISUALIZADOR_PUBLICARSERVICIO_SERVICENAME = "VISUALIZADOR.PUBLICARSERVICIO_SERVICENAME";
    public static String VISUALIZADOR_PUBLICARSERVICIO_WSDL = "VISUALIZADOR.PUBLICARSERVICIO_WSDL";
    public static String VISUALIZADOR_PUBLICARSERVICIO_ROL = "VISUALIZADOR.PUBLICARSERVICIO_ROL";
    public static String VISUALIZADOR_PUBLICARSERVICIO_MTOM = "VISUALIZADOR.PUBLICARSERVICIO_MTOM";
    // Agregado para modo compatibilidad
    public static String VISUALIZADOR_PUBLICARSERVICIO_VERSION = "VISUALIZADOR.PUBLICARSERVICIO_VERSION";

    public static String STS_URL = "STS_URL";
    public static String STS_POLITICA = "STS_POLITICA";
    public static String STS_EMISOR = "STS_EMISOR";
    public static String KEYSTORE_ORG_PATH = "KEYSTORE_ORG_PATH";
    public static String KEYSTORE_ORG_PASS = "KEYSTORE_ORG_PASS";
    public static String KEYSTORE_ORG_ALIAS = "KEYSTORE_ORG_ALIAS";
    public static String KEYSTORE_SSL_PATH = "KEYSTORE_SSL_PATH";
    public static String KEYSTORE_SSL_PASS = "KEYSTORE_SSL_PASS";
    public static String KEYSTORE_SSL_ALIAS = "KEYSTORE_SSL_ALIAS";
    public static String TRUSTSTORE_SSL_PATH = "TRUSTSTORE_SSL_PATH";
    public static String TRUSTSTORE_SSL_PASS = "TRUSTSTORE_SSL_PASS";

    public static String DOCUMENTOS_DIR = "DOCUMENTOS_DIR";
    public static String NOMBRE_ARCHIVO_MANUAL = "NOMBRE_ARCHIVO_MANUAL";

    public static String PROYECTO_GANTT_PERIODO = "PROYECTO_GANTT_PERIODO";

    public static String AUTH_LDAP_ENABLE = "AUTH_LDAP_ENABLE";
    public static String AUTH_LDAP_SEARCH_NAME = "AUTH_LDAP_SEARCH_NAME";
    public static String AUTH_LDAP_SEARCH_FILTER = "AUTH_LDAP_SEARCH_FILTER";
    public static String AUTH_LDAP_SEARCH_INITIAL_CTX_FACTORY = "AUTH_LDAP_SEARCH_INITIAL_CTX_FACTORY";
    public static String AUTH_LDAP_SEARCH_URL = "AUTH_LDAP_SEARCH_URL";
    public static String AUTH_LDAP_SECURITY_PRINCIPAL = "AUTH_LDAP_SECURITY_PRINCIPAL";
    public static String AUTH_LDAP_SECURITY_CREDENTIAL = "AUTH_LDAP_SECURITY_CREDENTIAL";
    public static String AUTH_LDAP_SEARCH_USER_LOGIN_FILTER = "AUTH_LDAP_SEARCH_USER_LOGIN_FILTER";

    public static String MEDIA_MIMETYPE_REGEX = "MEDIA_MIMETYPE_REGEX";

    // Modo depuración
    public static String DEBUG = "DEBUG";
    public static String DEBUG_DESTINO = "DEBUG_DESTINO";

    //Etiqueta de objetivos estrategicos
    public static String LABEL_OBJETIVO_ESTRATEGICO = "LABEL_OBJETIVO_ESTRATEGICO";

    public static String GOOGLE_API_KEY = "GOOGLE_API_KEY";

    public static String APROBACION_PMOF = "APROBACION_PMOF";
    public static String APROBACION_REPLANIFICACION_PMOF = "APROBACION_REPLANIFICACION_PMOF";
    
    public static String PERMITIR_REFERENCIAR_ENTREGABLES = "PERMITIR_REFERENCIAR_ENTREGABLES";

    public static String PROVEEDOR_ES_EXIGIDO_EN_PAGO = "PROVEEDOR_ES_EXIGIDO_EN_PAGO";

    public static String PROVEEDOR_ES_EXIGIDO_EN_COMPRA = "PROVEEDOR_ES_EXIGIDO_EN_COMPRA";


    public static String HABILITAR_MOVER_PROYECTO = "HABILITAR_MOVER_PROYECTO";
    
    public static String CLIENTE_ES_EXIGIDO_EN_PAGO = "CLIENTE_ES_EXIGIDO_EN_PAGO";
    
    public static String SHOW_MODULO_RIESGOS = "SHOW_MODULO_RIESGOS";
    public static String SHOW_MODULO_PRODUCTOS = "SHOW_MODULO_PRODUCTOS";
    public static String SHOW_MODULO_PRESUPUESTO = "SHOW_MODULO_PRESUPUESTO";
    public static String SHOW_MODULO_DOCUMENTOS = "SHOW_MODULO_DOCUMENTOS";
    public static String SHOW_MODULO_INTERESADOS = "SHOW_MODULO_INTERESADOS";
    public static String SHOW_MODULO_COLABORADORES = "SHOW_MODULO_COLABORADORES";
    public static String SHOW_MODULO_LOCALIZACIONES = "SHOW_MODULO_LOCALIZACIONES";
    public static String SHOW_MODULO_CALIDAD = "SHOW_MODULO_CALIDAD";
    public static String SHOW_MODULO_MULTIMEDIA = "SHOW_MODULO_MULTIMEDIA";
    public static String SHOW_MODULO_WEKAN = "SHOW_MODULO_WEKAN";
    public static String SHOW_MENU_EXPORTAR = "SHOW_MENU_EXPORTAR";
    public static String SHOW_MENU_HORAS_GASTOS_CALIDAD = "SHOW_MENU_HORAS_GASTOS_CALIDAD";
    
    public static String INCLUIR_CALCULAR_FINALIZADOS = "INCLUIR_CALCULAR_FINALIZADOS";
    public static String GERENTES_ASIGNAN_AREAS_TEMATICAS = "GERENTES_ASIGNAN_AREAS_TEMATICAS";
    public static String LARGO_MAXIMO_ID_ADQUISICION = "LARGO_MAXIMO_ID_ADQUISICION";

    public static String URL_SISTEMA = "URL_SISTEMA";

	public static String MATOMO_URL = "MATOMO_URL";
	public static String MATOMO_ID_SITIO = "MATOMO_ID_SITIO";
	public static String MATOMO_ID_DIMENSION_USUARIO = "MATOMO_ID_DIMENSION_USUARIO";
	public static String MATOMO_ID_DIMENSION_ORGANISMO = "MATOMO_ID_DIMENSION_ORGANISMO";
	
	public static final String WEKAN_ADMIN_USUARIO = "WEKAN_ADMIN_USUARIO";
	public static final String WEKAN_ADMIN_CONTRASENIA = "WEKAN_ADMIN_CONTRASENIA";
	public static final String WEKAN_SIGES_WEBHOOK = "WEKAN_SIGES_WEBHOOK";
	
	public static final String PMOF_COPIA_PROYECTOS = "PMOF_COPIA_PROYECTOS";
	public static final String PMOF_MODIFICA_METADATOS_PROYECTO = "PMOF_MODIFICA_METADATOS_PROYECTO";
	
	public static final String OCULTAR_IDENTIFICADORES_INICIO = "OCULTAR_IDENTIFICADORES_INICIO";
        
        public static final String PAGO_FILTRO_PROCEDIMIENTO_COMPRA="PAGO_FILTRO_PROCEDIMIENTO_COMPRA";
        public static final String CENTRO_DE_COSTO_EXIGIDO="CENTRO_DE_COSTO_EXIGIDO";
        public static final String PMOT_OMITIR_APROBACION_INICIAL="PMOT_OMITIR_APROBACION_INICIAL";
        public static final String PMOF_GESTIONA_SUS_PROYECTOS ="PMOF_GESTIONA_SUS_PROYECTOS";
        
         public static final String TIPO_ADQUISICION_REQUERIDO ="TIPO_ADQUISICION_REQUERIDO";
          public static final String ID_ADQUISICION_REQUERIDO ="ID_ADQUISICION_REQUERIDO";
           public static final String ACTIVAR_RANGOS_ID_ADQUISICION ="ACTIVAR_RANGOS_ID_ADQUISICION";
           
           public static final String PRIMERA_NOTIFICACION_INICIO_COMPRA="PRIMERA_NOTIFICACION_INICIO_COMPRA";
           public static final String SEGUNDA_NOTIFICACION_INICIO_COMPRA="SEGUNDA_NOTIFICACION_INICIO_COMPRA";
        
	
}
