package com.sofis.entities.codigueras;

/**
 * Constantes para usar en el atributo código de la configuracion.
 *
 * @author Usuario
 */
public class ConfiguracionCodigos {

    public static String IS_DESARROLLO = "IS_DESARROLLO";
    public static String DATABASE_ENGINE = "DATABASE_ENGINE";
    public static String DATABASE_SCHEMA = "DATABASE_SCHEMA";
    
    public static String FILTRO_INICIO_POR_AREAS = "FILTRO_INICIO_POR_AREAS";
    public static String RIESGO_TIEMPO_LIMITE_AMARILLO = "RIESGO_TIEMPO_LIMITE_AMARILLO";
    public static String RIESGO_TIEMPO_LIMITE_ROJO = "RIESGO_TIEMPO_LIMITE_ROJO";
    public static String RIESGO_INDICE_LIMITE_AMARILLO = "RIESGO_INDICE_LIMITE_AMARILLO";
    public static String RIESGO_INDICE_LIMITE_ROJO = "RIESGO_INDICE_LIMITE_ROJO";
    public static String RIESGO_FECHA_LIMITE_CANT_DIAS = "RIESGO_FECHA_LIMITE_CANT_DIAS";
    public static String DOCUMENTO_PORCENTAJE_LIMITE_AMARILLO = "DOCUMENTO_PORCENTAJE_LIMITE_AMARILLO";
    public static String DOCUMENTO_PORCENTAJE_LIMITE_ROJO = "DOCUMENTO_PORCENTAJE_LIMITE_ROJO";
    public static String TAMANIO_MAX_ARCHIVO_DOCUMENTO = "TAMANIO_MAX_ARCHIVO_DOCUMENTO";
    public static String TAMANIO_MAX_ARCHIVO_MULTIMEDIA = "TAMANIO_MAX_ARCHIVO_MULTIMEDIA";
    public static String COSTO_ACTUAL_LIMITE_AMARILLO = "COSTO_ACTUAL_LIMITE_AMARILLO";
    public static String COSTO_ACTUAL_LIMITE_ROJO = "COSTO_ACTUAL_LIMITE_ROJO";
    public static String ESTADO_INICIO_LIMITE_ROJO = "ESTADO_INICIO_LIMITE_ROJO";
    public static String ESTADO_INICIO_LIMITE_AMARILLO = "ESTADO_INICIO_LIMITE_AMARILLO";
    public static String ESTADO_PLANIFICACION_LIMITE_ROJO = "ESTADO_PLANIFICACION_LIMITE_ROJO";
    public static String ESTADO_PLANIFICACION_LIMITE_AMARILLO = "ESTADO_PLANIFICACION_LIMITE_AMARILLO";
    public static String PRODUCTO_INDICE_LIMITE_AMARILLO = "PRODUCTO_INDICE_LIMITE_AMARILLO";
    public static String PRODUCTO_INDICE_LIMITE_ROJO = "PRODUCTO_INDICE_LIMITE_ROJO";
    public static String ALCANCE_INDICE_LIMITE_AMARILLO = "ALCANCE_INDICE_LIMITE_AMARILLO";
    public static String ALCANCE_INDICE_LIMITE_ROJO = "ALCANCE_INDICE_LIMITE_ROJO";
    public static String TAMANIO_MAX_LOGO_ORGANISMO = "TAMANIO_MAX_LOGO_ORGANISMO";
    public static String MAIL_FROM = "MAIL_FROM";
    public static String MAIL_TLS = "MAIL_TLS";
    public static String MAIL_DEBUG = "MAIL_DEBUG";
    public static String MAIL_ENCODING = "MAIL_ENCODING";
    public static String CON_CORREO = "CON_CORREO";
    public static String CON_CONTROL_ACCESO = "CON_CONTROL_ACCESO";
    public static String ENVIO_NOTIFICACIONES = "ENVIO_NOTIFICACIONES";
    public static String HORA_NOTIFICACIONES = "HORA_NOTIFICACIONES";
    public static String ADJUNTO_MODIFICA_PRESUPUESTO = "ADJUNTO_MODIFICA_PRESUPUESTO";
    public static String CURRENT_LOCALE_LANGUAGE = "CURRENT_LOCALE_LANGUAGE";
    public static String CURRENT_LOCALE_COUNTRY = "CURRENT_LOCALE_COUNTRY";
    public static String CALIDAD_LIMITE_AMARILLO = "CALIDAD_LIMITE_AMARILLO";
    public static String CALIDAD_LIMITE_ROJO = "CALIDAD_LIMITE_ROJO";
    public static String CALIDAD_GERENTE_MODIFICA = "CALIDAD_GERENTE_MODIFICA";
    public static String FOLDER_MEDIA = "FOLDER_MEDIA";
    public static String USAR_PGE = "USAR_PGE";

    public static String VISUALIZADOR_EXPORTACION_POR_PGE = "VISUALIZADOR_EXPORTACION_POR_PGE";
    
    //Publicar Proyecto
    public static String VISUALIZADOR_PUBLICARSERVICIO_URLLOGICA = "VISUALIZADOR.PUBLICARSERVICIO_URLLOGICA";
    public static String VISUALIZADOR_PUBLICARSERVICIO_SOAPACTION = "VISUALIZADOR.PUBLICARSERVICIO_SOAPACTION";
    public static String VISUALIZADOR_PUBLICARSERVICIO_NAMESPACE = "VISUALIZADOR.PUBLICARSERVICIO_NAMESPACE";
    public static String VISUALIZADOR_PUBLICARSERVICIO_SERVICENAME = "VISUALIZADOR.PUBLICARSERVICIO_SERVICENAME";
    public static String VISUALIZADOR_PUBLICARSERVICIO_WSDL = "VISUALIZADOR.PUBLICARSERVICIO_WSDL";
    public static String VISUALIZADOR_PUBLICARSERVICIO_ROL = "VISUALIZADOR.PUBLICARSERVICIO_ROL";
    public static String VISUALIZADOR_PUBLICARSERVICIO_MTOM = "VISUALIZADOR.PUBLICARSERVICIO_MTOM";
    
    public static String STS_URL = "STS_URL";
    public static String STS_POLITICA = "STS_POLITICA";
    public static String STS_EMISOR = "STS_EMISOR";
    public static String KEYSTORE_ORG_PATH = "KEYSTORE_ORG_PATH";
    public static String KEYSTORE_ORG_PASS = "KEYSTORE_ORG_PASS";
    public static String KEYSTORE_ORG_ALIAS = "KEYSTORE_ORG_ALIAS";
    public static String KEYSTORE_SSL_PATH = "KEYSTORE_SSL_PATH";
    public static String KEYSTORE_SSL_PASS = "KEYSTORE_SSL_PASS";
    public static String KEYSTORE_SSL_ALIAS = "KEYSTORE_SSL_ALIAS";
    public static String TRUSTSTORE_SSL_PATH = "TRUSTSTORE_SSL_PATH";
    public static String TRUSTSTORE_SSL_PASS = "TRUSTSTORE_SSL_PASS";
    
    
    public static String DOCUMENTOS_DIR = "DOCUMENTOS_DIR";
    
    public static String PROYECTO_GANTT_PERIODO = "PROYECTO_GANTT_PERIODO";

}
