//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.04 at 07:00:16 PM UYST 
//


package uy.gub.agesic.pge.core.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uy.gub.agesic.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uy.gub.agesic.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PGEConfig.STSConfig }
     * 
     */
    public PGEConfig.STSConfig createPGEConfigSTSConfig() {
        return new PGEConfig.STSConfig();
    }

    /**
     * Create an instance of {@link PGEConfig.STSConfig.Property }
     * 
     */
    public PGEConfig.STSConfig.Property createPGEConfigSTSConfigProperty() {
        return new PGEConfig.STSConfig.Property();
    }

    /**
     * Create an instance of {@link PGEConfig }
     * 
     */
    public PGEConfig createPGEConfig() {
        return new PGEConfig();
    }

    /**
     * Create an instance of {@link PGEConfig.KeyStore.Auth }
     * 
     */
    public PGEConfig.KeyStore.Auth createPGEConfigKeyStoreAuth() {
        return new PGEConfig.KeyStore.Auth();
    }

    /**
     * Create an instance of {@link PGEConfig.KeyStore }
     * 
     */
    public PGEConfig.KeyStore createPGEConfigKeyStore() {
        return new PGEConfig.KeyStore();
    }

}
