/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sofis.agesic.siges.migrador;

import static com.sofis.agesic.siges.migrador.IComunicacion.Tipo.MENSAJE;

/**
 *
 * @author spio
 */
public class Migrador1 extends javax.swing.JFrame implements IComunicacion {

  String viejoHost;
  String viejoPort;
  String viejoBase;
  String viejoUser;
  String viejoPass;
  String nuevoHost;
  String nuevoPort;
  String nuevoBase;
  String nuevoUser;
  String nuevoPass;

  String nombreOrganismo;
  String directorioArchivos;
  boolean limpiar;
  boolean sinProductos;
  
  public Migrador1(String viejoHost, String viejoPort, String viejoBase, String viejoUser,
          String viejoPass, String nuevoHost, String nuevoPort, String nuevoBase, String nuevoUser,
          String nuevoPass, String nombreOrganismo, String directorioArchivos, boolean limpiar, boolean sinProductos) {

    this.viejoHost = viejoHost;
    this.viejoPort = viejoPort;
    this.viejoBase = viejoBase;
    this.viejoUser = viejoUser;
    this.viejoPass = viejoPass;

    this.nuevoHost = nuevoHost;
    this.nuevoPort = nuevoPort;
    this.nuevoBase = nuevoBase;
    this.nuevoUser = nuevoUser;
    this.nuevoPass = nuevoPass;

    this.nombreOrganismo = nombreOrganismo;
    this.directorioArchivos = directorioArchivos;
    this.limpiar = limpiar;
    this.sinProductos = sinProductos;
    
    initComponents();
    
    Migrador2 migrador2 = new Migrador2(this, viejoHost, viejoPort, viejoBase, viejoUser, 
            viejoPass, nuevoHost, nuevoPort, nuevoBase, nuevoUser, nuevoPass, nombreOrganismo, 
            directorioArchivos, limpiar, sinProductos);
    migrador2.start();
    
    
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    sclSalida = new javax.swing.JScrollPane();
    txtMensajes1 = new javax.swing.JTextArea();
    jPanel2 = new javax.swing.JPanel();
    sclSalida1 = new javax.swing.JScrollPane();
    txtMensajes2 = new javax.swing.JTextArea();
    jPanel3 = new javax.swing.JPanel();
    sclSalida2 = new javax.swing.JScrollPane();
    txtMensajes3 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    txtMensajes1.setColumns(20);
    txtMensajes1.setRows(5);
    sclSalida.setViewportView(txtMensajes1);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(sclSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(sclSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Progreso", jPanel1);

    txtMensajes2.setColumns(20);
    txtMensajes2.setRows(5);
    sclSalida1.setViewportView(txtMensajes2);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(sclSalida1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(sclSalida1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Script SQL", jPanel2);

    txtMensajes3.setColumns(20);
    txtMensajes3.setRows(5);
    sclSalida2.setViewportView(txtMensajes3);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(sclSalida2, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(sclSalida2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        .addContainerGap())
    );

    jTabbedPane1.addTab("Mapeos", jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTabbedPane1)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JScrollPane sclSalida;
  private javax.swing.JScrollPane sclSalida1;
  private javax.swing.JScrollPane sclSalida2;
  private javax.swing.JTextArea txtMensajes1;
  private javax.swing.JTextArea txtMensajes2;
  private javax.swing.JTextArea txtMensajes3;
  // End of variables declaration//GEN-END:variables

  @Override
  public void mostrarMensaje(Tipo t, String m) {
    switch(t) {
      case MENSAJE:
        txtMensajes1.append(m+"\n");
        break;
      case SENTENCIASQL:
        txtMensajes2.append(m+"\n");
        break;
      case MAPEO:
        txtMensajes3.append(m+"\n");
        break;
    }
  }
}
